### ISSUE TITLE
explicit `toFront` call for `show-window`

### ISSUE THREAD

**Issue by hoebat** [generateme/cljplot#1]
When `show` is called, the graph does not appear at the front.

A `java.awt.Window.toFront()` call needs to be made in order to get the window to appear.

https://github.com/Clojure2D/clojure2d/blob/master/src/clojure2d/core.clj#L2102

**Comment by genmeblog** [comment]
yes, it's clojure2d bug, it will be fixed soon.

**Comment by genmeblog** [comment]
fixed in clojure2d snapshot

**Comment by genmeblog** [comment]
not fixed :/
