### ISSUE TITLE
grid layout for graphs

### ISSUE THREAD

**Issue by hoebat** [generateme/cljplot#13]
Is it possible to define a grid and layout plots using a defined layout?

ie Total Grid is divided into [4x4] squares

plot A at [0 0] having size [2 4]
plot B at [2 0] having size [2 2]
plot C at [2 2] having size [2 2]

**Comment by hoebat** [comment]
Another way would just be to generate those plots separately then stitch them together.

**Comment by genmeblog** [comment]
Current renderer allows only regular grid layout. So you have to render charts separately and merge them externally.
When I think about different layouts, they should be possible without changing whole building process. So maybe in the future grid span would be possible.

**Comment by hoebat** [comment]
Sweet. It’s easy to stitch them together. I’ll close this for now.
