### ISSUE TITLE
Source for results/bubble.jpg?

### ISSUE THREAD

**Issue by richhickey** [generateme/cljplot#16]
Hi, 

I was wondering where I might find the source that produced results/bubble.jpg. I see many of the source files for /results in /sketches, but I can't seem to find this one.

Thanks,
Rich

**Comment by genmeblog** [comment]
Hi Rich, it's a result of first experiments which I had outside this repo. Just fixed this and you can find the code here: https://github.com/generateme/cljplot/blob/master/sketches/examples.clj#L366

This one uses callbacks to let user control size and data. Some charts allow functions in the configuration. Such function receives data record (first parameter) and whole configuration (second).

I'm thinking about removing this feature eventually and let user just map data->parameter automatically somehow.

**Comment by richhickey** [comment]
Thanks!
