### ISSUE TITLE
how to change the background color of the plot?

### ISSUE THREAD

**Issue by hoebat** [generateme/cljplot#5]
It's currently light grayish blue and I want to set it to white.

**Comment by genmeblog** [comment]
there is a rendering parameter `:background`.

`(r/render-lattice {:width 400 :height 400 :background :white})`

**Comment by genmeblog** [comment]
Just to note, background can be color or image.

Color can be a keyword from this list: https://clojure2d.github.io/clojure2d/docs/static/colors.html or ARGB integer: `0xffaabbcc` or CSS string "#bbaacc" or sequence of 3 (r,g,b) or 4 elements (r,g,b,a).

Image can be loaded by `(clojure2d.core/load-image "path")`

**Comment by hoebat** [comment]
sweet. thanks.
